

services:
  my-shop-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge